kind: pipeline
type: docker
name: traefik-deploy

steps:
  - name: deploy
    image: docker:latest
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock
    commands:
      - apk add --no-cache docker-compose

      # Ensure acme.json exists with correct permissions
      # - touch acme.json
      # - chmod 600 acme.json

      # Deploy Traefik
      - docker-compose down || true
      - docker-compose up -d

      # Show status
      # - docker-compose ps
      # - docker logs traefik --tail 10
