# This file is no longer used - migrated to Docker auto-discovery
# Traefik now uses Docker labels for service discovery
# See docker-compose.yaml files for service configurations
# 
# Backup of original config saved as config.yml.backup

# Static file configuration has been replaced with:
# - Docker provider in traefik.yml
# - Service labels in individual docker-compose.yml files